<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Nota;

class NotasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $notas = [
            [
                'alumno' => 157,
                'lapso' => '1er Lapso',
                '1era' => 15,
                '2da' => 20,
                '3era' => 20,
                '4ta' => 18,
                'adicionales' => 0,
                'total' => 18,
                'idMa' => 114,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '1er Lapso',
                '1era' => 13,
                '2da' => 17,
                '3era' => 15,
                '4ta' => 20,
                'adicionales' => 0,
                'total' => 16,
                'idMa' => 116,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '1er Lapso',
                '1era' => 16,
                '2da' => 20,
                '3era' => 14,
                '4ta' => 20,
                'adicionales' => 0,
                'total' => 18,
                'idMa' => 117,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '2do Lapso',
                '1era' => 17,
                '2da' => 10,
                '3era' => 17,
                '4ta' => 17,
                'adicionales' => 0,
                'total' => 15,
                'idMa' => 114,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '2do Lapso',
                '1era' => 13,
                '2da' => 19,
                '3era' => 15,
                '4ta' => 15,
                'adicionales' => 0,
                'total' => 16,
                'idMa' => 116,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '2do Lapso',
                '1era' => 18,
                '2da' => 13,
                '3era' => 12,
                '4ta' => 20,
                'adicionales' => 0,
                'total' => 16,
                'idMa' => 117,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '3er Lapso',
                '1era' => 20,
                '2da' => 15,
                '3era' => 17,
                '4ta' => 14,
                'adicionales' => 0,
                'total' => 17,
                'idMa' => 114,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '3er Lapso',
                '1era' => 11,
                '2da' => 17,
                '3era' => 18,
                '4ta' => 20,
                'adicionales' => 0,
                'total' => 17,
                'idMa' => 116,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '3er Lapso',
                '1era' => 12,
                '2da' => 12,
                '3era' => 16,
                '4ta' => 14,
                'adicionales' => 0,
                'total' => 14,
                'idMa' => 117,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '1er Lapso',
                '1era' => 16,
                '2da' => 11,
                '3era' => 13,
                '4ta' => 14,
                'adicionales' => 0,
                'total' => 14,
                'idMa' => 113,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '1er Lapso',
                '1era' => 12,
                '2da' => 10,
                '3era' => 12,
                '4ta' => 13,
                'adicionales' => 0,
                'total' => 12,
                'idMa' => 115,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '2do Lapso',
                '1era' => 11,
                '2da' => 11,
                '3era' => 9,
                '4ta' => 13,
                'adicionales' => 0,
                'total' => 11,
                'idMa' => 113,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '2do Lapso',
                '1era' => 8,
                '2da' => 12,
                '3era' => 5,
                '4ta' => 20,
                'adicionales' => 0,
                'total' => 11,
                'idMa' => 115,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '3er Lapso',
                '1era' => 10,
                '2da' => 10,
                '3era' => 13,
                '4ta' => 14,
                'adicionales' => 0,
                'total' => 12,
                'idMa' => 113,
                'curso' => 59,
                'periodo' => 16,
            ],
            [
                'alumno' => 157,
                'lapso' => '3er Lapso',
                '1era' => 10,
                '2da' => 13,
                '3era' => 13,
                '4ta' => 20,
                'adicionales' => 0,
                'total' => 14,
                'idMa' => 115,
                'curso' => 59,
                'periodo' => 16,
            ],
        ];

        foreach ($notas as $nota) {
            Nota::create($nota);
        }
    }
}
